dataset: ogbg-molhiv
aug: baseline
model_type: gnn-transformer
gnn_type: gin
gnn_virtual_node: false
graph_pooling: cls
runs: 10
seed: 12344
batch_size: 256
lr: 0.0001
start-eval: 1

d_model: 128
dim_feedforward: 256
num_encoder_layers: 4
scheduler: plateau

nhead: 4
transformer_norm_input: true
gnn_dropout: 0.3
gnn_JK: cat
